workflows:
  android-workflow-id:
    name: Android Sample Workflow
    environment:
      java: 17
    # .......
    # .......
    # .......
  ios-workflow-id:
    name: iOS Sample Workflow
    # ......